const CDN_LINK ="";
const LOGO_LINK = "";
const RESTAURANT_LIST = [
  {
    "id": "rest_001",
    "name": "The Velvet Apron",
    "cuisine": "Modern European",
    "rating": 4.7,
    "review_count": 312,
    "price_level": "$$$",
    "address": "124 Artisan Way, Downtown",
    "latitude": 40.7128,
    "longitude": -74.0060,
    "is_open_now": true,
    "image_url": "https://unsplash.com"
  },
  {
    "id": "rest_002",
    "name": "Taco Fiesta",
    "cuisine": "Mexican Street Food",
    "rating": 4.3,
    "review_count": 850,
    "price_level": "$",
    "address": "582 Mercado Blvd, West End",
    "latitude": 40.7150,
    "longitude": -74.0110,
    "is_open_now": true,
    "image_url": "https://unsplash.com"
  },
  {
    "id": "rest_003",
    "name": "Sakura Sushi",
    "cuisine": "Japanese & Sushi",
    "rating": 4.8,
    "review_count": 195,
    "price_level": "$$$$",
    "address": "88 Zen Lane, Midtown",
    "latitude": 40.7090,
    "longitude": -74.0015,
    "is_open_now": false,
    "image_url": "https://unsplash.com"
  },
  {
    "id": "rest_004",
    "name": "The Daily Grind Cafe",
    "cuisine": "Bakery & Coffee",
    "rating": 4.5,
    "review_count": 420,
    "price_level": "$$",
    "address": "12 Roasted Beans St, Arts District",
    "latitude": 40.7210,
    "longitude": -74.0080,
    "is_open_now": true,
    "image_url": "https://unsplash.com"
  },
  {
    "id": "rest_005",
    "name": "Burger Foundry",
    "cuisine": "Gourmet Burgers",
    "rating": 4.2,
    "review_count": 610,
    "price_level": "$$",
    "address": "77 Sizzle Ave, Northside",
    "latitude": 40.7185,
    "longitude": -73.9985,
    "is_open_now": true,
    "image_url": "https://unsplash.com"
  },
  {
    "id": "rest_006",
    "name": "Olive & Vine",
    "cuisine": "Mediterranean Bistro",
    "rating": 4.6,
    "review_count": 275,
    "price_level": "$$$",
    "address": "404 Coastal Road, Waterfront",
    "latitude": 40.7020,
    "longitude": -74.0150,
    "is_open_now": true,
    "image_url": "https://unsplash.com"
  },
  {
    "id": "rest_007",
    "name": "Curry Leaves",
    "cuisine": "Traditional Indian",
    "rating": 4.4,
    "review_count": 530,
    "price_level": "$$",
    "address": "93 Spice Market Row, East Side",
    "latitude": 40.7250,
    "longitude": -73.9910,
    "is_open_now": false,
    "image_url": "https://unsplash.com"
  },
  {
    "id": "rest_008",
    "name": "Bella Italia",
    "cuisine": "Italian & Pasta",
    "rating": 4.9,
    "review_count": 1102,
    "price_level": "$$$$",
    "address": "14 Roma Court, Little Italy",
    "latitude": 40.7198,
    "longitude": -73.9970,
    "is_open_now": true,
    "image_url": "https://unsplash.com"
  },
  {
    "id": "rest_009",
    "name": "The Green Bowl",
    "cuisine": "Salads & Vegan",
    "rating": 4.1,
    "review_count": 142,
    "price_level": "$$",
    "address": "22 Sprouts Lane, Financial District",
    "latitude": 40.7065,
    "longitude": -74.0095,
    "is_open_now": true,
    "image_url": "https://unsplash.com"
  },
  {
    "id": "rest_010",
    "name": "Smokey's BBQ",
    "cuisine": "American Smokehouse",
    "rating": 4.5,
    "review_count": 689,
    "price_level": "$$",
    "address": "808 Charcoal Dr, Industrial Park",
    "latitude": 40.7300,
    "longitude": -74.0200,
    "is_open_now": false,
    "image_url": "https://unsplash.com"
  }
]